Proposal: Add mapping symbol
riscv-non-isa/riscv-elf-psabi-doc pull request #196
Opened 2021-07-08 07:25 UTC by kito-cheng

# What is Mapping Symbol

This proposal add a new special symbol class, called mapping symbol,
those symbol are used for assist disassembler to having better knowledge
of binary, it could be used for distinguish the code and data region.

Here is two kind of mapping symbol: data and instruction, and both
having an optional extra part in the symbol name for carry extra information.

Symbol Name | Meaning
:---------- | :-----------------------------------------------------------
$d          | Start of a sequence of data.
$d\<N\>       | Start of a sequence of N-byte data.
$x          | Start of a sequence of instructions.
$x\<ISA\>     | Start of a sequence of instructions with \<ISA\> extension.

Mapping symbol are also used by other ISA for same purpose, like ARM, AArch64,
C-sky and nds32.

# Data Mapping Symbol

Data mapping symbol could having an extra length information to present
the orignal data layout.

e.g.
```
.foo:
	.word 10
	.byte 1
	.word 20
	.byte 2
```

Without mapping symbol:
```
$ riscv64-unknown-elf-gcc foo.s -c
$ riscv64-unknown-elf-gcc foo.o -c

Disassembly of section .text:

0000000000000000 <.foo>:
   0:   000a                    c.slli  zero,0x2
   2:   0000                    unimp
   4:   1401                    addi    s0,s0,-32
   6:   0000                    unimp
   8:   0200                    addi    s0,sp,256
```

With mapping symbol:
```
Disassembly of section .text:

00000000 <.foo>:                                      # $d insert here.
   0:   0000000a        .word   0x0000000a
   4:   00001401        .word   0x00001401
   8:   Address 0x0000000000000008 is out of bounds.
```

With mapping symbol + extra length information:
```
Disassembly of section .text:

00000000 <.foo>:
   # $d4 insert here.
   0:   0000000a        .word   0x0000000a
   # $d1 insert here.
   4:   01              .byte   0x01
   # $d4 insert here.
   5:   00000014        .word   0x00000014
   # $d1 insert here.
   9:   02              .byte   0x01
```

# Instruction Mapping Symbol

Instruction mapping symbol with extra ISA info could also used for
ifunc, e.g. library are built with `rv64gc`, but few functions
like memcpy provide two version, one built with `rv64gc`, and one built with
`rv64gcv`, and select by ifunc mechanism at run-time; however the arch
attribute is recording for minimal execution environment requirement, so the ISA
information from arch attribute isn't enough for disassembler to disassemble the
`rv64gcv` version correctly.

2021-07-09 09:03 UTC, Nelson1225 commented
Hi Guys,

This PR LGTM, thanks for Kito's help.

The v2 proposed patch in binutils is as follows,
https://sourceware.org/pipermail/binutils/2021-July/117316.html

However, compared to the current implementation, there are some issues that might be worth discussing.

* $d<N>, N is data length.

The length is only attached when the data is added by cons_worker.  List all possible cases as follows,
`.byte`, `.hword`, `.int`, `.long`, `.octa`, `.quad`, `.short`, `.word`, `.2byte`, `.4byte`, `.8byte`, `.dc`, `.dc.a`, `.dc.b`, `.dc.l`, `.dc.w`, `.rva`.

For the .fill data directive, or rs_align, I still use a $d without data length to mark the region, since it is hard to estimate the length when adding the mapping symbols.  Besides, the initial purpose is to display the code which are written by users more closely, the .fill data are originally a directive to represent a data region, so add the data length to the $d seems redundant.

Therefore, it would be great if we can add - `$d<N>, N is 1, 2, 4, 8`.

* $a1 for odd byte code alignment, $a for a region of code alignment.

Consider the following case, which is compiled by the old toolchain without the mapping symbols.
$ cat tmp.s
        .text
        .option norvc
        .option norelax
        .byte   1
        .align  3
        nop
$ riscv64-unknown-elf-as tmp.s -o tmp.o
$ riscv64-unknown-elf-objdump -d tmp.o
0000000000000000 <.text>:
   0:   0001                    nop
   2:   0001                    nop
   4:   00000013            nop
   8:   00000013            nop
   c:   00000013            nop

There are two problems here,
1. The `.byte` + part of `.align 3` is recognized to a c.nop instruction.
2. c.nop is illegal since `.option norvc` is used.

But if we add mapping symbols for the case, then we can get the more friendly result,
0000000000000000 <.text>:
   0:   01                      .byte   0x01
   1:   00                      align.byte
   2:   0001                  align.nop
   4:   00000013          align.nop
   8:   00000013          nop
   c:   00000013          align.nop

$a1 is added at address 0x1, which is the start of the `.align 3`.  And then $a is added at 0x1 + 0x1 = 0x2.  If we don't add the $a1, then we will get the following result, 
0000000000000000 <.text>:
   0:   01                      .byte   0x01
   1:   0100                   align.addi      s0,sp,128
   3:   1300                   align.addi      s0,sp,416
   5:   0000                   align.unimp
   7:   1300                   align.addi      s0,sp,416
   9:   0000                   unimp
   b:   1300                   addi    s0,sp,416
   d:   0000                   align.unimp

Umm seems like objdump decode the `.align.byte` as a part of instruction `addi`.  However, we also can improve the objdump, so maybe it could dump the correct results without the $a1 mapping symbol.  I believe this is feasible, but use $a1 is quit easy, and no harm, at least to me.

* The documentation for -D says that on ARM platforms -D should disassemble instructions.  Therefore, they dump data by searching mapping symbols only when the DISASSEMBLE_DATA is set.  That causes the mapping symbols are useless for -D.  I am not sure if any riscv document had mentioned this, so I prefer to keep them useful, but only for text sections.  Otherwise, dump other sections as data.

2021-07-09 16:57 UTC, jrtc27 commented
align.byte and align.nop are not valid mnemonics/directives. There is no need for special markers for alignment bytes, just fix the disassembler to correctly handle:
```
$d:
    .byte 1
$x:
    .byte half_of_a_c_nop(?)
    c.nop
```
i.e. don't try to disassemble instructions that are at odd addresses after data regions (or anything other than 0 mod 4 if RVC isn't present).

2021-07-09 17:00 UTC, jrtc27 commented on riscv-elf.md
> +$x<ISA>     | Start of a sequence of instructions with <ISA> extension.
You don't need length information for data; it doesn't exist for real `.data` sections, it doesn't need to exist for `.text` either, just put a `$d` at the start and a `$x` at the end.

You also need to allow the `$d.foo`/`$x<ISA>.foo` form for cases where manual mapping symbols are being added to assembly files, as otherwise you get duplicate symbol definitions. The `.foo` is used to make them all unique, but is completely ignored.

2021-07-09 17:02 UTC, jrtc27 commented on riscv-elf.md
> +and it has an optional ISA string, which means following code region are using
You need to state what the rules are for the ISA string; is it anything valid for -march= (ie default versions, implied extensions, etc all supported) or is it like the .RISCV.attributes section where it must be the full exploded string?

2021-07-11 13:48 UTC, kito-cheng commented on riscv-elf.md
> +$x<ISA>     | Start of a sequence of instructions with <ISA> extension.
> You also need to allow the $d.foo/$x<ISA>.foo form for cases where manual mapping symbols are being added to assembly files, as otherwise you get duplicate symbol definitions. The .foo is used to make them all unique, but is completely ignored.

Suffix is not needed since mapping symbol local symbol, that could verified by AArch64 or ARM.

2021-07-11 13:49 UTC, jrtc27 commented on riscv-elf.md
> +$x<ISA>     | Start of a sequence of instructions with <ISA> extension.
You can't specify the same symbol twice in the same assembly file. That's what the suffix is for.

2021-07-11 14:01 UTC, kito-cheng commented on riscv-elf.md
> +$x<ISA>     | Start of a sequence of instructions with <ISA> extension.
> You don't need length information for data; it doesn't exist for real .data sections, it doesn't need to exist for .text either, just put a $d at the start and a $x at the end.

That was designed for text section, used for mixing data and instruction, here is an example[1] from linux kernel, there is few data are put in text, and data having `.word`(32 bits) and `.dword`(64 bits), length information can provide better disassemble output here. 

[1] https://github.com/torvalds/linux/blob/master/arch/riscv/kernel/head.S#L52

2021-07-11 14:09 UTC, kito-cheng commented
> The objudmp -D make mapping symbols useless for ARM/AARCH64.
The documentation for -D says that on ARM platforms -D should disassemble instructions. Therefore, they dump data by searching mapping symbols only when the DISASSEMBLE_DATA is set. That causes the mapping symbols are useless for -D. I am not sure if any riscv document had mentioned this, so I prefer to keep them useful, but only for text sections. Otherwise, dump other sections as data.

I would prefer don't write down the behavior, it's a hit, how to interpreter that is dependent on implementation.

2021-07-11 16:39 UTC, jrtc27 commented on riscv-elf.md
> +$x<ISA>     | Start of a sequence of instructions with <ISA> extension.
But if I do:
```
.data
    .dword 0
    .byte 1
```
then there is no length information there. Having mapping symbols to switch between code and data in .text is sufficient to achieve parity with how .data gets dumped. This adds unnecessary complexity.

2021-07-11 18:54 UTC, MaskRay commented
I do see a use case for `$d<N>` yet.

I have some experience with the llvm-objdump and llvm-symbolizer. llvm-symbolizer just excludes mapping symbols. llvm-objdump adds mapping symbols of the current section into a sorted vector and performs a binary search. `$d<N>` will be ignored anyway. If you don't ignore `$d<N>`, you will need additional verification complexity I don't know will be justified.

---

I cannot find `$d.<suffix>` `$x.<suffix>` `$t.<suffix>` usage in a hand-written assembly file other than lld/gas testsuites. I think it is fine not to define it for now.

2021-07-13 10:13 UTC, Nelson1225 commented
Thanks for your suggestions, @jrtc27 @MaskRay and @kito-cheng, I have sent v3 series of patches as follows,
https://sourceware.org/pipermail/binutils/2021-July/117348.html

Compared to v2,

* Removed the data mapping symbols with data size.

* Removed the alignment mapping symbols, $a and $a1.

* If the alignment have odd bytes spaces and relaxation
  is disable, we usually remain an odd byte 0x00 at the
  start of alignment, and then fill nops for the remianing
  spaces.  Therefore, add a $d mapping symbol for the odd
  byte, and then add a $x at $d + 0x1.  This behavior is
  same as Arm and Aarch64.

Thanks
Nelson

2021-07-22 13:44 UTC, kito-cheng commented on riscv-elf.md
> +$x<ISA>     | Start of a sequence of instructions with <ISA> extension.
`$d<N>` is removed, I agree that it's unnecessary complexity, and might increase symbol table.

2021-07-22 13:51 UTC, kito-cheng commented
Updates:
- Remove `$d`
- add rule for `$x<ISA>`

2021-07-22 19:52 UTC, jim-wilson reviewed
Looks OK to me.  Could use a little English improvement, but that can wait until enough people are OK with it.  No need to rewrite the English multiple times.

2021-07-22 19:52 UTC, jim-wilson commented on riscv-elf.md
> +without without ISA string means using ISA configuration from ELF attribute.
```suggestion
without ISA string means using ISA configuration from ELF attribute.
```

2021-07-22 19:52 UTC, jim-wilson commented on riscv-elf.md
> +and it has an optional ISA string, which means following code region are using
Below it says that the string must be same as Tag_RISCV_arch.

2021-08-12 04:29 UTC, kito-cheng commented
Changes:
- Mark use case part as `NOTE`.
- Add one more note about toolchain implementation, allow linker to merge mapping symbol and allow strip tool to strip mapping symbol.

2021-08-12 06:17 UTC, kito-cheng commented
Changes:
- Rebase to `master`

2021-08-30 07:31 UTC, kito-cheng commented
Changes:
- Rebase to master

2021-08-30 07:32 UTC, kito-cheng commented
@jrtc27 @MaskRay could you take a look? :)

2021-08-31 20:48 UTC, MaskRay requested changes

2021-08-31 20:48 UTC, MaskRay commented on riscv-elf.adoc
> +Mapping symbol is a special symbol class used for assist disassembler to
I'd say that a section can have a mixture of code and data. Mapping symbols describe the boundaries.

2021-08-31 20:48 UTC, MaskRay commented on riscv-elf.adoc
> +| $x<ISA>     | Start of a sequence of instructions with <ISA> extension.
Better to follow arm's lead by requiring a bot: `$x.<any>`

2021-08-31 20:48 UTC, MaskRay commented on riscv-elf.adoc
> +Format and rule of the optional ISA string is same as Tag_RISCV_arch, must
Reserving `$x.<any>` is more useful than defining it just for ISA.
I am not sure specifying an ISA is useful, or needed to be defined now.

`$x` and `$d` have clear usefulness and can be added today.

2021-08-31 20:48 UTC, MaskRay commented on riscv-elf.adoc
> +NOTE: For toolchain implementation, linker are permit to merge the adjacency
adjacent mapping symbols if they are of

2021-08-31 21:30 UTC, jrtc27 commented on riscv-elf.adoc
> +Format and rule of the optional ISA string is same as Tag_RISCV_arch, must
Changing the ISA for disassembly is the primary reason why this is needed on RISC-V (nobody really cares about constant pools that much otherwise we'd see mapping symbols on more architectures). We need a way to have, say, an RV64GC binary that has snippets of RV64GCV in it, and whilst you could introduce some kind of "max ISA" attribute to go alongside the current ISA attribute in .riscv.attributes (which is the "I need this to be able to run" attribute), that doesn't work once you have conflicting extensions (e.g. you might want F and Zfinx in the same binary, or the ratified V spec with XOldVSpecBecauseVendorImplementedAnEarlyDraftDespiteClearDocumentationEverywhereThisShouldNotBeDone).

2021-08-31 21:34 UTC, MaskRay commented on riscv-elf.adoc
> +Format and rule of the optional ISA string is same as Tag_RISCV_arch, must
Your description makes sense. The original wording based on ifunc scared me.

Still worth thinking how if we ever need `<any>`, where to place it. `$x<isa>.<any>`?

2021-08-31 21:39 UTC, jrtc27 commented on riscv-elf.adoc
> +Format and rule of the optional ISA string is same as Tag_RISCV_arch, must
Yeah, the `.<any>` is a meaningless uniquifier, so would go on the end after the actually-significant ISA.

2021-09-24 09:14 UTC, kito-cheng commented on riscv-elf.adoc
> +NOTE: For toolchain implementation, linker are permit to merge the adjacency
Updated, thanks :)

2021-09-24 09:15 UTC, kito-cheng commented on riscv-elf.adoc
> +Format and rule of the optional ISA string is same as Tag_RISCV_arch, must
Added one sentence to allow an optional suffix uniquifier string.

2021-09-24 09:15 UTC, kito-cheng commented
Changes:
- Rebase
- Allow an optional suffix uniquifier string for mapping symbol name.
- Revise wording per @MaskRay's suggestion

2021-10-01 09:40 UTC, kito-cheng commented
Changes:
- Rebase
- Revise description of mapping symbol

2022-11-24 13:18 UTC, kito-cheng commented
Changes:
- Rebase
-  Wording and grammar tweaks.

2023-01-30 07:51 UTC, kito-cheng commented
We have landed mapping symbol on binutils site and having patch under review on LLVM land (https://reviews.llvm.org/D137417).

@MaskRay Do you mind give a blessing to this PR? :)

2023-02-02 03:30 UTC, MaskRay approved these changes

2023-02-02 03:30 UTC, MaskRay commented on riscv-elf.adoc
> +mapping symbol is a special symbol class used to describe the boundaries.
I haven't seen a term named "symbol class". Avoid it?

`; mapping symbol ...` => `. A number of symbols, named mapping symbols, describe the boundaries`.

Mention that they have type `STT_NOTYPE`, binding `STB_LOCAL`, and size zero.

2023-02-02 03:30 UTC, MaskRay commented on riscv-elf.adoc
> +The mapping symbol for data(`$d`) means the following region is data.
indicates the start of a sequence of data bytes.

2023-02-02 03:30 UTC, MaskRay commented on riscv-elf.adoc
> +The mapping symbol for instruction(`$x`) means the following region are
indicates the start of a sequence of instructions.

2023-02-02 03:30 UTC, MaskRay commented on riscv-elf.adoc
> +Format and rule of the optional ISA string are same as Tag_RISCV_arch, must
backticks around `Tag_RISCV_arch`

The format of the optional ISA string

2023-02-02 03:30 UTC, MaskRay commented on riscv-elf.adoc
> +NOTE: For toolchain implementation, the linker is permitted to merge the
Does GNU ld combine adjacent mapping symbols? How GNU strip removes mapping symbols is complex. 

That would be a weird thing to do. Consider dropping this sentence.

2023-02-02 03:31 UTC, MaskRay commented on riscv-elf.adoc
> +| $x<ISA>     | Start of a sequence of instructions with <ISA> extension.
`$x.<ISA>`

2023-02-02 03:42 UTC, jrtc27 commented on riscv-elf.adoc
> +| $x<ISA>     | Start of a sequence of instructions with <ISA> extension.
The <any> is a uniquifier. The <ISA> is the ISA to use. $x.<ISA> would then be ambiguous if we permit Arm's uniquifier approach where you can add anything after a . to work around assemblers that don't like duplicate symbols.

2023-02-20 12:00 UTC, kito-cheng commented on riscv-elf.adoc
> +mapping symbol is a special symbol class used to describe the boundaries.
Thanks, added one more sentence to describe the type, binding and size.

2023-02-20 12:01 UTC, kito-cheng commented on riscv-elf.adoc
> +NOTE: For toolchain implementation, the linker is permitted to merge the
Removed, currently binutils didn't implement both.

2023-02-20 12:04 UTC, kito-cheng commented on riscv-elf.adoc
> +| $x<ISA>     | Start of a sequence of instructions with <ISA> extension.
Yeah, I would prefer keep same since we have slightly difference between ARM's mapping symbol, or maybe we could add `$x.<any>` and `$x<ISA>.<any>` to allow we have uniquifier like ARM?

2023-02-20 12:05 UTC, kito-cheng commented
Changes:
- Rebase.
- Mention mapping symbol has type STT_NOTYPE, binding STB_LOCAL, and size zero.
- Wording tweaks.

2023-03-14 13:57 UTC, kito-cheng commented
Got approve from LLD and binutils maintainer, gonna merge this :)

2023-03-14 14:02 UTC, merged

2023-03-14 19:09 UTC, jrtc27 commented on riscv-elf.adoc
> +| $x<ISA>     | Start of a sequence of instructions with <ISA> extension.
We should IMO

2023-03-22 15:49 UTC, kito-cheng commented on riscv-elf.adoc
> +| $x<ISA>     | Start of a sequence of instructions with <ISA> extension.
https://github.com/riscv-non-isa/riscv-elf-psabi-doc/pull/372