Clarify the range of medlow code model on rv64
riscv-non-isa/riscv-elf-psabi-doc pull request #241
Opened 2022-01-13 03:41 UTC by kito-cheng

Range of medlow code model is highest 2GiB and lowest 2GiB, but the spec
only say lowest 2GiB.

And also put the detail to show how those range come from.

Ref:
[1] https://www.sifive.com/blog/all-aboard-part-4-risc-v-code-models

2022-01-13 03:41 UTC, kito-cheng commented
@palmer-dabbelt

2022-01-14 00:12 UTC, nick-knight commented
Looks like this was introduced in https://github.com/riscv-non-isa/riscv-elf-psabi-doc/pull/153.

@jim-wilson pointed it out in his review https://github.com/riscv-non-isa/riscv-elf-psabi-doc/pull/153#discussion_r443149571, which apparently wasn't addressed.

2022-01-14 06:04 UTC, kito-cheng commented
@nick-knight thanks for dig out the history :)

2022-03-30 07:33 UTC, kito-cheng commented
Changes:
- Rebase

2022-04-02 12:09 UTC, jrtc27 reviewed
Went ahead and fixed the grammar myself; please check you still agree with what's written

2022-04-02 12:09 UTC, jrtc27 commented on riscv-elf.adoc
> +addi, a0, a0, 0xfffffffffffff800 # a0 = a0 + -2048 = 0xFFFFFFFF7FFFF800
Should this be written -0x800? Both LLVM and binutils accept this syntax but it's not so clear and a bit misleading.

2022-04-04 05:59 UTC, kito-cheng commented on riscv-elf.adoc
> +addi, a0, a0, 0xfffffffffffff800 # a0 = a0 + -2048 = 0xFFFFFFFF7FFFF800
Yeah, `-0x800` is much clear than `0xfffffffffffff800` and verified with GNU and LLVM that produce same result.

2022-04-04 06:00 UTC, kito-cheng commented
Changes:
- Apply @jrtc27's suggestion

2022-04-04 14:05 UTC, nick-knight requested changes

2022-04-04 14:05 UTC, nick-knight commented on riscv-elf.adoc
> +lui a0, 0x7ffff # a0 = 0x7ffff
I think you're missing a couple trailing zeros in the comment.

2022-04-04 14:43 UTC, kito-cheng commented
Changes:
- Fix wrong comment on calculate the medlow range for rv64

2022-04-04 15:20 UTC, nick-knight requested changes

2022-04-04 15:20 UTC, nick-knight commented on riscv-elf.adoc
> +`0xFFFFFFFF7FFFF800` ~ `0xFFFFFFFFFFFFFFFF` due to RISC-V's sign-extension of
Um, the second range _is_ correct, though, right? (Copy/paste error?)

2022-04-06 11:04 UTC, kito-cheng commented on riscv-elf.adoc
> +`0xFFFFFFFF7FFFF800` ~ `0xFFFFFFFFFFFFFFFF` due to RISC-V's sign-extension of
`0xFFFFFFFF7FFFF800` is what I want since `0xFFFFFFFF7FFFF800` lowest address in the highest 2GiB.

See
```
# Smallest negative number:
lui a0, 0x80000 # a0 = 0xffffffff80000000
addi a0, a0, -0x800 # a0 = a0 + -2048 = 0xFFFFFFFF7FFFF800
```

2022-04-06 12:49 UTC, jrtc27 commented on riscv-elf.adoc
> +`0xFFFFFFFF7FFFF800` ~ `0xFFFFFFFFFFFFFFFF` due to RISC-V's sign-extension of
Compare with how 0x7fffffff is the number given here for the low range

2022-04-06 13:20 UTC, jrtc27 approved these changes

2022-04-06 13:22 UTC, merged

2022-04-07 09:31 UTC, luismarques commented on riscv-elf.adoc
> +# Largest postive number:
Sorry for not commenting on time on this but here's a typo to fix in a follow-up PR: "postive".