Add details of .riscv.attributes section layout
riscv-non-isa/riscv-elf-psabi-doc pull request #357
Opened 2023-01-09 20:58 UTC by vineetgarc

Signed-off-by: Vineet Gupta <vineetg@rivosinc.com>

2023-01-09 21:19 UTC, jrtc27 requested changes

2023-01-09 21:19 UTC, jrtc27 commented on riscv-elf.adoc
> +The attributes section contains a header (different from the elf section header)
This seems like an odd thing to say, especially when the format is then documented

2023-01-09 21:19 UTC, jrtc27 commented on riscv-elf.adoc
> +  uint8 : format-version: 'A'
This is the only thing in the header

2023-01-09 21:19 UTC, jrtc27 commented on riscv-elf.adoc
> +  NTBS  : "riscv\0"
These are the subsection header, where "riscv\0" is the vendor

2023-01-09 21:19 UTC, jrtc27 commented on riscv-elf.adoc
> +  uint32: sub-section length (excludes itself)
This is the "sub-subsection" (Arm's name) header (the format of a subsection is determined based on the vendor, but we use the same format as identified by Arm's "aeabi" vendor name), and the format you're documenting (the only one RISC-V is using) is for Tag_File (the others are deprecated for Arm), which you need to document as being 1.

2023-01-09 21:19 UTC, jrtc27 commented on riscv-elf.adoc
> +  uint8 : Tag_Section (uleb128 encoded)
This being uleb128 is rather hypothetical when the only valid values are 1-3... but uint8 disagrees with uleb128

2023-01-09 21:19 UTC, jrtc27 commented on riscv-elf.adoc
> +The actual attributes follow directly as tag:value pairs, terminated by a '\0'
They're not terminated by anything (maybe you're getting confused by Tag_Section and Tag_Symbol having a 0 byte separator between the section/symbol numbers and attributes list)

2023-01-09 21:19 UTC, jrtc27 commented on riscv-elf.adoc
> +and one or more sub-sections. As of now it only contains one sub-section.
In theory vendors are free to add their own... that's why the vendor string exists (and "[Aa]non.*" is reserved for custom use by Arm)

2023-01-09 21:51 UTC, vineetgarc commented on riscv-elf.adoc
> +  uint32: sub-section length (excludes itself)
ok yeah makes sense now that read the ARM elf sepc - my initial interpretation was just reverse engineering from binutils code.

2023-01-09 21:52 UTC, vineetgarc commented on riscv-elf.adoc
> +  uint8 : Tag_Section (uleb128 encoded)
Right

2023-01-09 21:53 UTC, vineetgarc commented on riscv-elf.adoc
> +The actual attributes follow directly as tag:value pairs, terminated by a '\0'
there is a tag 0 at the end to signify end of sub-section which also doubles as string terminator in case the last tag/vaue is a NTBS.

2023-01-09 21:57 UTC, jrtc27 commented on riscv-elf.adoc
> +The actual attributes follow directly as tag:value pairs, terminated by a '\0'
According to what? The string terminator is always there and is part of the attribute, and if you have a ULEB128 then the final byte isn't 0.

2023-01-09 21:58 UTC, jrtc27 commented on riscv-elf.adoc
> +The actual attributes follow directly as tag:value pairs, terminated by a '\0'
What you've documented would have _two_ zero bytes at the end of the last string and a zero byte on the end of the last ULEB128.

2023-01-09 22:00 UTC, vineetgarc commented on riscv-elf.adoc
> +  uint8 : Tag_Section (uleb128 encoded)
FWIW unlike the ARM spec, the RV byte-size encoding for Tag_file doesn't include the lengths of tag or byte-size fields.

```
  [25] .riscv.attributes RISCV_ATTRIBUTE  0000000000000000  000b5e78
       0000000000000066  0000000000000000           0     0     1
                    ^^^ (length)
‘A’   sub-sec length    ‘r’  ‘i’  ‘s’  ‘c’ ‘v’ ‘\0’
41     65 0 0 0             72 69 73 63 76 0 

Tag-file   byte-size (of following contents)
1            5b 0 0 0
```

2023-01-09 22:01 UTC, vineetgarc commented on riscv-elf.adoc
> +The actual attributes follow directly as tag:value pairs, terminated by a '\0'
Right I understand and will fix that.

2023-01-09 22:04 UTC, vineetgarc commented on riscv-elf.adoc
> +The attributes section contains a header (different from the elf section header)
I was meaning to clarify that this is an "inline" header within the section as opposed to actual section table entry / header for this section as I got confused initially. But it was all muddled up due to section / sub-section confusion. But as you say the header part here is just 'A' so need not be called out as header per se.

2023-01-09 22:15 UTC, jrtc27 commented on riscv-elf.adoc
> +  uint8 : Tag_Section (uleb128 encoded)
Yes it does. 0x65 == 0x5b + (4 + 6), the subsection header size

2023-01-09 22:18 UTC, vineetgarc commented on riscv-elf.adoc
> +  uint8 : Tag_Section (uleb128 encoded)
there are 2 length fields here: the first one includes itself, the second one is data length and for ARM that includes the attr tag and itself, whereas it doesn't for RV.

Quoting ARM spec [1]
```
In each case, byte-size is a 4-byte unsigned integer in the byte order of the ELF file. Byte-size includes the initial tag byte, the size field itself, and the sub-subsection content. That is, it is the byte offset from the start of this sub-subsection to the start of the next sub-subsection.```

[1] https://github.com/ARM-software/abi-aa/blob/main/addenda32/addenda32.rst#representing-build-attributes-in-elf-files

2023-01-09 22:32 UTC, jrtc27 commented on riscv-elf.adoc
> +  uint8 : Tag_Section (uleb128 encoded)
Yes it does for RISC-V. They are the same. I don't see how the readelf output you gave earlier demonstrates otherwise; I just showed how it _does_ add up.

2023-01-09 22:36 UTC, vineetgarc commented on riscv-elf.adoc
> +  uint8 : Tag_Section (uleb128 encoded)
You showed how 065 = 0x5b + 4 + 6  - we aagree there as 0x65 includes itself (not the intiail 'A' fwiw)

What I'm saying is that 0x5b doesn't include self length and tag length - because if it would then it would be 0x65 - 4 = 0x61 not 0x5b

2023-01-09 22:37 UTC, jrtc27 commented on riscv-elf.adoc
> +  uint8 : 1 (Tag_File)
It's legal to have more than one file sub-subsection as far as I can tell, they just behave as if you concatenated them all together

2023-01-09 22:39 UTC, jrtc27 commented on riscv-elf.adoc
> +  uint8 : Tag_Section (uleb128 encoded)
What is "self length" and "tag length"? 0x5b is 0x66 minus the "sub-sec length" (4 bytes) and "riscv\0" (6 bytes) as in your dump above, that is it is the size of the entire sub-subsection, _including_ the sub-subsection header.

2023-01-09 22:42 UTC, vineetgarc commented on riscv-elf.adoc
> +  uint8 : Tag_Section (uleb128 encoded)
/me slaps myself - you are right of course - i was just overlooking the string chars themselves :-(

2023-01-11 01:11 UTC, jrtc27 commented on riscv-elf.adoc
> +The vendor name "[An]non" is reserved by ARM.
1. [Aa] not [An]
2. It's all vendors that start with that, which is why I said "[Aa]non.*"
3. Arm reserve it for their section, but this isn't Arm's section, it's ours, which is the same format as theirs but isn't theirs, so it's not really reserved by Arm here. Also, saying it's reserved by Arm isn't helpful, it's reserved by Arm _for unregistered private use_, which for us would be nonstandard ABI extensions (mirroring the terminology used earlier for relocations). So just say they're reserved for nonstandard ABI extensions.

2023-01-11 22:24 UTC, vineetgarc commented on riscv-elf.adoc
> +  uint8 : 1 (Tag_File)
ARM has deprecated Tag_section, Tag_symbol. Do we intend to introduce them to riscv abi or just have Tag_File.
Assuming it is latter is it still possible to have multiple of them - in RV ABI
I need to add Tag_file to the doc, should we add the rest as well ?

2023-01-11 22:25 UTC, vineetgarc commented on riscv-elf.adoc
> +The vendor name "[An]non" is reserved by ARM.
OK.

2023-01-12 20:50 UTC, vineetgarc commented
I've revised the contents per review and force pushed the PR.

Thx,

2023-01-30 04:13 UTC, kito-cheng reviewed
Just a nit, otherwise LGTM :)

2023-01-30 04:13 UTC, kito-cheng commented on riscv-elf.adoc
> +Sub-sub-section Tag Tag_RISCV_file (value 1) specifies that contained attibutes
Tag_RISCV_file -> Tag_File, the term is used in binutils and LLVM source tree.

2023-01-30 20:54 UTC, vineetgarc commented on riscv-elf.adoc
> +Sub-sub-section Tag Tag_RISCV_file (value 1) specifies that contained attibutes
Fixed and force pushed branch !

2023-02-06 03:10 UTC, kito-cheng approved these changes
LGTM, wait one week to make sure no further comment.

2023-02-20 06:21 UTC, merged