Add note for array with empty struct or union
riscv-non-isa/riscv-elf-psabi-doc pull request #365
Opened 2023-02-10 09:41 UTC by kito-cheng

Fix #358

The key point of this issue is C and C++ having different type size for array of empty struct or union, size of empty struct or union is 0 for C, and 1 for C++, and the size of array is type size multiplied by the length of the array.

Also checked AArch64 code gen, they also generated different code between C and C++, and ABI isn't explicitly describe this but has describe the size of array is type * length.

2023-02-10 16:40 UTC, asb commented
Thanks for looking at this Kito. Quick high level comment: I think the case of a zero-length array of empty structs/unions should also be mentioned. Perhaps it's worth being more explicit about the case of a 1-sized array of an empty struct/union too?

2023-02-16 16:01 UTC, kito-cheng commented
Changes:
- Add example to show the case `struct { struct {} e[1]; float f; };`
- Add sentence to mention zero-length array will ignored during struct flatten.

2023-02-16 18:25 UTC, nick-knight requested changes

2023-02-16 18:25 UTC, nick-knight commented on riscv-cc.adoc
> +destructors.  Fields containing zero-length bit-fields or zero-length array are
Grammatical suggestion:

```suggestion
destructors.  Fields containing zero-length bit-fields or zero-length arrays are
```

2023-02-16 18:25 UTC, nick-knight commented on riscv-cc.adoc
> +NOTE: One exceptional case for the flattening rule is the array with empty
Minor English suggestion:

```suggestion
NOTE: One exceptional case for the flattening rule is an array of empty
```

2023-02-16 18:25 UTC, nick-knight commented on riscv-cc.adoc
> +structs or unions; C language treats it as an empty field, but {Cpp} language
Minor English suggestion:

```suggestion
structs or unions; C treats it as an empty field, but {Cpp}
```

2023-02-16 18:25 UTC, nick-knight commented on riscv-cc.adoc
> +empty struct or union having a different size between C and {Cpp}. i.e.
Delete redundant sentence and s/i.e./e.g.

```suggestion
or union as 1. E.g.,
```

2023-02-16 18:25 UTC, nick-knight commented on riscv-cc.adoc
> +
`f0` is `ft0`: I think you mean `fa0`. 

Also, we're not using a fixed-width font for register mnemonics elsewhere, so I suggest not introducing it here and now.

Also a minor English suggestion.

```suggestion
for `struct { struct {} e[1]; float f; };`, C will pass `f` in fa0, but {Cpp} will
pass it in `a0`.
```

2023-02-16 18:25 UTC, nick-knight commented on riscv-cc.adoc
> +
My experiment on LLVM for this example is showing the same result for C and C++. But having just embarrassed myself over at #366 I am very hesitant to say any more.

2023-02-16 18:29 UTC, asb commented on riscv-cc.adoc
> +
I opened #358 as it seemed Clang/LLVM wasn't matching GCC. My patch https://reviews.llvm.org/D142327 _should_ match the clarification in this PR but it hasn't been committed yet.

2023-02-16 19:40 UTC, nick-knight commented on riscv-cc.adoc
> +
Thanks @asb . I think I understand how things work. I've updated my suggestion above to clarify some of my confusions.

2023-02-20 09:13 UTC, kito-cheng commented
@nick-knight thanks for your comment and suggestion :)

2023-03-14 14:07 UTC, kito-cheng commented
@asb @jrtc27 @luismarques did you mind take a review for that? I would like to have your review before I merge that :)

2023-03-14 16:42 UTC, luismarques approved these changes

2023-03-14 16:45 UTC, luismarques commented
Sorry, I shouldn't have approved this. What is there LGTM but it doesn't explicitly cover all cases that @asb was asking about.

2023-03-23 10:08 UTC, kito-cheng commented
@luismarques  added more description for zero-length array of empty structs/union, thank for the review :)

2023-03-23 10:11 UTC, kito-cheng commented
Changes:

- Explicitly say the field with array of empty struct type will be ignored or not in the example.

2023-03-30 10:36 UTC, asb commented
@kito-cheng the last round of grammatical suggestions from @nick-knight are marked as resolved but the changes don't seem to be reflected in the current version of the patch. It looks like they might have got lot along the way?

2023-03-30 10:36 UTC, asb commented on riscv-cc.adoc
> +destructors.  Fields containing zero-length bit-fields or zero-length array are
This was marked resolved but doesn't seem to have been integrated.

2023-04-03 10:42 UTC, asb approved these changes
LGTM modulo the minor wording fixes suggested in line. Thanks Kito!

2023-04-03 10:42 UTC, asb commented on riscv-cc.adoc
> +The zero-length arrays of empty structs or union will treat be
The zero-length => Zero-length
will treat be => will be

2023-04-03 10:42 UTC, asb commented on riscv-cc.adoc
> +ignored for bot C and {Cpp}. i.e. For `struct { struct {} e[0]; float f; };`,
bot => both

2023-05-17 13:24 UTC, merged