[RFC] Relax gp could be platform specific register rather than reserved for…
riscv-non-isa/riscv-elf-psabi-doc pull request #371
Opened 2023-03-22 14:22 UTC by kito-cheng

… linker relaxation

The usage of gp register has discussed serveral times (e.g. #298), and it reserved as special register used for linker relaxation, that could be improve perfomance and code size.

However it come with some limitation, like it can't applicable on shared libraries, and it also not work well when program come with large datas since the relaxable range is only +-2KiB.

Some platform like Haiku never use gp in the whole system, and also this might not useful in some baremetal system with specialized memory layout, so we might consider to release the gp usage with a non-hard-ABI-breakage way.

This proposal also adding a tag for preventing mix objects with different gp register usage.

2023-03-24 01:18 UTC, appujee commented
SGTM. Thanks for proposing this.

For reference: More discussion around this has been going on in: https://lists.riscv.org/g/sig-toolchains/topic/97736679#548 and https://github.com/riscv-non-isa/riscv-elf-psabi-doc/issues/370

2023-03-24 04:49 UTC, rui314 commented
Different platforms might want to use the "platform register" for different purposes, no? If so, just defining `1` for the platform register cannot prevent incompatible object files to be linked to a single executable. We might want to define a value for each specific usage.

2023-03-27 09:34 UTC, kito-cheng commented
@rui314 good point, I add 2 range for standard and non-stanadrd use used range, and also one for undefined one.

2023-03-27 09:52 UTC, rui314 commented
I'm not sure what the undefined purpose is. Maybe we just want to reserve 2-1024 for the standard uses and 1025-2047 for nonstandard uses?

2023-03-27 14:30 UTC, kito-cheng commented
My first thought about that undefined purpose is kind of reserved for nonstandard use, but we already defined one range for nonstandard, so yeah, that should be just 2-1024 for the standard uses and 1025-2047 for nonstandard uses

2023-03-28 05:27 UTC, MaskRay commented on riscv-elf.adoc
> +0:: This object use gp as global pointer relaxation.
What value is defined for unused gp?

2023-03-28 21:24 UTC, appujee commented on riscv-elf.adoc
> +0:: This object use gp as global pointer relaxation.
Even if gp is unused, is it safe to assume that gp is used for global pointer relaxation? As this has been the default behavior.

Can there be cases where gp is allowed for global pointer relaxation and no such opportunities were found in the binary?

2023-03-29 13:32 UTC, kito-cheng commented on riscv-elf.adoc
> +0:: This object use gp as global pointer relaxation.
> Can there be cases where gp is allowed for global pointer relaxation and no such opportunities were found in the binary?

In theory we can made one program with a symbol with huge size (large then 4k) and point `__global_pointer$` to the middle of the symbol, then the global pointer relaxation will have no way to relax anything, but that case should not happened in generally since `__global_pointer$` is default computed by a magic (or heuristic) expression with some arithmetic with sbss/sdata.

2023-03-29 13:41 UTC, kito-cheng commented
Changes:
- Add `unused` case
- Drop `undefined` case
- Made 3~1023 as reserved for future standard defined platform register.

NOTE: GP as SCS will defined in separated PR.

2023-03-30 02:06 UTC, kito-cheng commented
> Honestly I don't feel good to add Tag_RISCV_gp_reg_usage now. There are many C++ dialect affecting -f options, yet we don't have compatibility attributes for them. AArch64 has SHT_AARCH64_ATTRIBUTES, but it isn't really used.

IMO that could be used to sanity check and identity some information how this object/executable compiled, otherwise the only way is writing some magic script/tools to check that like https://github.com/google/android-riscv64/issues/77 mentioned, a binary validator...

`-frecord-command-line ` might be another way, but some info. might not able to know from command line since some setting might be implied by default configuration or target triple, so that's not a reliable way.

There is many C++ dialect, one recent happened example is [relative vtables ABI for C++](https://youtu.be/9HGKlDiJy8E), I didn't ask to add a tag to identify that is because it's still `experimental` (`-fexperimental-relative-c++-abi`) (I didn't express this at that PR I know, but that's what I thought and I should say that out at that time...).

Anyway, my point is we should track/record those information if possible, adding attributes could help tool to having better diagnosis message instead of silently broken, otherwise people don't have too much clue to tracking what happened when screw up things.

2023-03-30 02:27 UTC, MaskRay commented
If a source file uses inline assembly to initialize gp, we can't know how the user intends to use gp. For GP relaxation, the use case is done in the final link phase. The compile phases don't know and should not need to use an option to tell the compiler *not* to create an attribute/note indicating GP relaxation.

I don't deny that a compatibility detecting feature may be useful, but we don't need to do it now. (For this case I suspect I slightly lean toward never having it.) If we want to do it, it can be a separate proposal. I have seen a lot of inconvenience in binutils/glibc adding some compatibility detecting feature and I strongly believe waiting a bit will have a large value.

2023-04-04 06:56 UTC, kito-cheng commented
@MaskRay Thanks for sharing your thought , split `Tag_RISCV_gp_reg_usage` out, and that also made this PR become no PoC required, and that's kind of big change to RISC-V ABI, so I would like to get you explicitly LGTM :)

2023-04-04 07:15 UTC, kito-cheng commented
@asb @luismarques although `gp` only used in linker relaxation stage, so per our policy that only require consensus from linker gurus, but it's a big change so I would like to make sure RISC-V LLVM maintainer is OK with this.

@rui314 you are linker expert, and I would like all linker expert is happy with this change.

@Nelson1225 I need your opinion as binutils expert :) 

@jrtc27 FreeBSD didn't use gp relaxation, so I guess you are fine with this change, but I would like you give explicitly LGTM to this one if possible :)

2023-04-06 05:40 UTC, asb commented
> @asb @luismarques although `gp` only used in linker relaxation stage, so per our policy that only require consensus from linker gurus, but it's a big change so I would like to make sure RISC-V LLVM maintainer is OK with this.

I think although platforms can of course deviate from the standard ABI however they wish, having a suggested register for platform specific purposes makes sense. GP is convenient for this purpose and there seem to be no strong concerns about it, so all LGTM.

I think you need to update the commit message so it no longer claims to introduce a new tag (as this was dropped for now I believe).

2023-04-06 05:50 UTC, asb commented on riscv-cc.adoc
> +Platform might use gp register as platform specific register other than used for
How about "If a platform requires use of a dedicated general-purpose register for a platform-specific purpose, it is recommended to use gp (x3). The platform ABI specification must document the use of this register and care must be taken to disable global pointer relaxation in toolchains when targeting that platform."

2023-04-06 05:53 UTC, asb commented
I've left a suggested wording change for the actual patch part of this (inspired partially by #374). I don't think we should equate gp just with gp relaxation, as it might e.g. be used in hand-written assembly.

2023-04-06 06:24 UTC, appujee commented on riscv-cc.adoc
> +Platform might use gp register as platform specific register other than used for
Should we also specify that, when **gp** is reserved for a platform-specific purpose:
- Toolchain may not allocate **gp** for any other purpose than for platform-specific purpose.
- Care must be taken while compiling assembly code as it may be using **gp**  in undesired ways.

IMO It would help to add a note that as per the current spec, the compiler does not add a tag in ELF that would indicate the way **gp** is being used. given a pre-built binary, **gp** might be getting used either for platform-specific purpose or for global pointer relaxation. The onus of ensuring **gp** is being used as intended lies entirely on the consumer of a pre-built binary.

2023-04-06 09:38 UTC, aswaterman requested changes
I disagree with the premise of this PR.  A platform might choose to designate _any_ register as used for an alternate purpose.  No matter which register is chosen, it affects the ABI somehow.

2023-04-06 09:43 UTC, jrtc27 commented
> No matter which register is chosen, it affects the ABI somehow.

Which is why we're constraining it so it's *not* a free-for-all. Otherwise you end up in a situation where something like OpenSSL needs a different copy of its crypto assembly routines for each platform because it needs to avoid each platform's reserved register. The whole point of a specification like a psABI is to impose order on the chaos so everyone agrees on what is going on; if you want to allow any register to be reserved by any platform and remain standards-compliant then why bother having an ABI at all?

2023-04-06 09:46 UTC, aswaterman commented
@jrtc27 indeed I perceive the intent to reserve `gp` to be part of a free-for-all promulgated by people who hate linker relaxation as a concept.  This is not a process; it's a mob.

2023-04-06 09:47 UTC, jrtc27 commented
> @jrtc27 indeed I perceive the intent to reserve `gp` to be that of a free-for-all promulgated by people who hate linker relaxation as a concept. This is not a process; it's a mob.

This is not constructive, nor is it factually accurate. Please take this rhetoric elsewhere; it has no place in the RISC-V community.

2023-04-06 09:49 UTC, aswaterman approved these changes

2023-04-06 10:09 UTC, aswaterman commented
> Before further discussing which register to specify, I wanted to check if you disagree that's there's any value at all in giving such a hint?

Of course, I agree there's value in doing so.

> is it that choosing gp for this platform specific register might be seized upon to force a decision in a particular direction in any future debate about gp relaxations?

That was precisely my point, although I failed to articulate it politely.

2023-04-06 14:19 UTC, asb commented
> > is it that choosing gp for this platform specific register might be seized upon to force a decision in a particular direction in any future debate about gp relaxations?
> 
> That was precisely my point, although I failed to articulate it politely.

It's probably a good thing to discuss this concern explicitly though I think.

So for my part, my LGTM on this specific change is not indicative of any point of view on the best use of GP in the standard ABI as already implemented. I suspect there will be recurrent discussions about it because if you want to scavenge a register for another purpose, GP is going to be near the top of the list. But I see this PR as separate to any such discussion.

2023-04-06 15:38 UTC, appujee commented
> @jrtc27 indeed I perceive the intent to reserve gp to be that of a free-for-all promulgated by people who hate linker relaxation as a concept. This is not a process; it's a mob.

AIUI, the range of gp is small (+/- 2kb) and probably that's why we haven't seen compiler optimizations leveraging that.  To the best of my knowledge, none of the Android libraries use gp. If you have ideas on how gp can help in platforms like Android, it will be good to share such that we can realize the trade-offs being made here.

2023-04-06 15:42 UTC, jrtc27 commented
> > @jrtc27 indeed I perceive the intent to reserve gp to be that of a free-for-all promulgated by people who hate linker relaxation as a concept. This is not a process; it's a mob.
> 
> AIUI, the range of gp is small (+/- 2kb) and probably that's why we haven't seen compiler optimizations leveraging that. To the best of my knowledge, none of the Android libraries use gp. If you have ideas on how gp can help in platforms like Android, it will be good to share such that we can realize the trade-offs being made here.

GP relaxation is only usable by executables, not libraries, since it takes a constant value throughout execution and thus libraries would compete for its use (though I guess there's an interesting question of whether one could designate a specific library as being the One True GP User, like libc). If I remember correctly, someone from Google in the call on Monday (Elliott?) said that ~everything is a library on Android, which would explain why GP relaxation is not of much use to them? (Though perhaps something like ART could then be blessed as the One True GP User...)

2023-04-06 17:16 UTC, ilovepi commented
@aswaterman I'm not sure where you stand on this change, given that you've approved it now, but your comments seem to conflict with that sentiment. Can you provide some clarification on your stance and any lingering concerns?

2023-04-06 17:32 UTC, aswaterman commented
Although I remain concerned that this choice might be speciously used as a pretext to stop using gp relaxations in existing ABIs, I agree with @asb that this PR can go through without addressing that matter.

2023-04-06 18:07 UTC, appujee approved these changes
LGTM the intent of the patch. As I mentioned in the review, it will be nice to have some explanation on the a) use case b) requirements on the toolchain, and c) risks of using gp for platform-specific purpose without a tag.

2023-04-06 18:49 UTC, asb commented on riscv-cc.adoc
> +Platform might use gp register as platform specific register other than used for
I don't feel particularly strongly, but I'm not sure it's worth going into details about the lack of an ELF tag. I don't think ELF tags are a good match for something at this level (after all, they're no help at all for inline assembly). I'm normally in favour of being a bit verbose to be more easily understandable, but I'm not sure further spelling out how gp can't be used for anything other than the platform-specific purpose adds a lot. But happy to go along with it if others feel differently.

Perhaps:
"If a platform requires use of a dedicated general-purpose register for a platform-specific purpose, it is recommended to use gp (x3). The platform ABI specification must document the use of this register. For such platforms, care must be taken to ensure all code (compiler generated or otherwise) avoids using gp in a way incompatible with the platform specific purpose, and that global pointer relaxation is disabled in the toolchain."

2023-04-07 07:40 UTC, kito-cheng commented
@aswaterman I guess I might give you impression that I am not support GP relaxation in #298, but I believe you know that I did know the value of GP relaxation in specific areas, especially on the small bare-metal system, and it also gives us some extra spec score, so I am not intending to deprecate the GP relaxation. 

For the SCS, the ideal case is using Zisslpcfi extension, but that would be an issue since it’s not ready now, and also it still require several psABI works (not only SCS, but also landing pad stuffs), so we need to figure out a way to make it moving forward, and GP is the relative best candidate so far.

And of course that’s kind of a mistake that we didn’t learn from other platforms - we didn’t reserve a platform register at the beginning, picking any other general purpose register as platform register would be more painful at this moment.

2023-04-07 07:47 UTC, kito-cheng commented on riscv-cc.adoc
> +Platform might use gp register as platform specific register other than used for
@asb thanks a lot for improving the text! hope you don't mind I listed you as co-author in this patch :)

2023-04-07 07:48 UTC, kito-cheng commented
Changes:
- Rebase
- Apply @asb's suggesion

2023-04-07 07:48 UTC, kito-cheng commented
Thanks everyone, It seems we have converged on this topic, I would like to wait few more day to make sure no further comment before merge :)

2023-04-11 03:07 UTC, X547 commented on riscv-elf.adoc
> +0:: This object use gp as global pointer relaxation.
> Even if gp is unused, is it safe to assume that gp is used for global pointer relaxation?

It seems not. Operating system may not initialize GP with `__global_pointer` and leave it with zero or some undefined value. Haiku for example do not define or use `__global_pointer` because it do not distinguish executables and shared libraries.

2023-04-11 03:30 UTC, X547 commented
> GP relaxation is only usable by executables, not libraries, since it takes a constant value throughout execution and thus libraries would compete for its use (though I guess there's an interesting question of whether one could designate a specific library as being the One True GP User, like libc).

PowerPC ABI have similar concept to GP register (TOC register R2) that also works in shared libraries by using special library calling convention with switching TOC register to address of called shared library and switch back on return.

> If I remember correctly, someone from Google in the call on Monday (Elliott?) said that ~everything is a library on Android, which would explain why GP relaxation is not of much use to them?

The same for Haiku. Executables and shared libraries are the same except NULL entry point is allowed for shared libraries, but not for executables.

2023-04-11 21:48 UTC, MaskRay approved these changes
Thanks for the update. The new wording looks good to me.

2023-04-14 08:24 UTC, kito-cheng commented
> PowerPC ABI have similar concept to GP register (TOC register R2) that also works in shared libraries by using special library calling convention with switching TOC register to address of called shared library and switch back on return.

@X547  thanks for provide this info, that's interesting idea we could consider in embedded ABI I think.

2023-04-14 08:24 UTC, merged

2023-04-14 08:24 UTC, kito-cheng commented
Thanks everyone again :)

2023-04-14 19:43 UTC, MaskRay commented
> > PowerPC ABI have similar concept to GP register (TOC register R2) that also works in shared libraries by using special library calling convention with switching TOC register to address of called shared library and switch back on return.
> 
> @X547 thanks for provide this info, that's interesting idea we could consider in embedded ABI I think.

@X547 I don't think PowerPC64 ELFv2 TOC is a good design:) (I have many lld patches in this area) See my summary of TOC on https://maskray.me/blog/2023-02-26-linker-notes-on-power-isa

2023-04-14 21:08 UTC, X547 commented
> the compiler inserts a NOP after the branch instruction.

Can be relaxed, no?

2023-04-14 21:16 UTC, MaskRay commented
> > the compiler inserts a NOP after the branch instruction.
> 
> Can be relaxed, no?

It can, but I am unsure about the linker complexity.

Their mere existence makes a tail call no longer a tail cal. I have summarized all sorts of maintenance costs on https://maskray.me/blog/2023-02-26-linker-notes-on-power-isa

2023-06-09 09:25 UTC, kito-cheng commented
https://github.com/riscv-non-isa/riscv-elf-psabi-doc/pull/387 for adding new tag for recording gp usage

2025-03-01 02:22 UTC, 578881718 commented
Hello, I would like to ask why not add an add instruction to expand the range of gp to 32bits, but it is only +/-2k.